using System.Text;
using System.Text.Json;
using DeckDoctor.Core.Models;

namespace DeckDoctor.Core.Services;

/// <summary>Result of a batched Scryfall name lookup — found cards keyed by the name you asked with, plus which names came back unresolved.</summary>
public record ScryfallLookupResult(Dictionary<string, ScryfallCard> Found, List<string> NotFound);

public class ScryfallClient
{
    private readonly HttpClient _http;
    private const int BatchSize = 75; // Scryfall's documented max for /cards/collection

    public ScryfallClient(HttpClient? http = null)
    {
        _http = http ?? new HttpClient();
        // Scryfall asks API consumers to identify themselves; also good practice generally.
        _http.DefaultRequestHeaders.UserAgent.ParseAdd("DeckDoctor/1.0 (personal Commander deck analysis tool)");
        _http.DefaultRequestHeaders.Accept.ParseAdd("application/json");
    }

    /// <summary>Fetch full card data for a list of card names via /cards/collection, batched at 75/request.</summary>
    public async Task<ScryfallLookupResult> FetchCardsByNameAsync(IEnumerable<string> names)
    {
        var distinctOriginal = names.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        var result = new Dictionary<string, ScryfallCard>(StringComparer.OrdinalIgnoreCase);
        var notFound = new List<string>();

        // Archidekt names double-faced/split cards as "Front // Back" — confirmed against a real
        // response that Scryfall's /cards/collection wants just the front face for lookup by
        // name (both of Council of Four's not_found entries were exactly this pattern). Query
        // with the front-face-only name, but keep a map back to the original so results/failures
        // report using the name the caller actually passed in.
        var queryToOriginal = distinctOriginal.ToDictionary(
            n => n.Contains(" // ") ? n[..n.IndexOf(" // ", StringComparison.Ordinal)] : n,
            n => n,
            StringComparer.OrdinalIgnoreCase);
        var queryNames = queryToOriginal.Keys.ToList();

        for (int i = 0; i < queryNames.Count; i += BatchSize)
        {
            var batch = queryNames.Skip(i).Take(BatchSize).ToList();
            var identifiers = batch.Select(n => new Dictionary<string, string> { ["name"] = n });
            var payload = JsonSerializer.Serialize(new { identifiers });

            using var req = new HttpRequestMessage(HttpMethod.Post, "https://api.scryfall.com/cards/collection")
            {
                Content = new StringContent(payload, Encoding.UTF8, "application/json"),
            };
            var resp = await _http.SendAsync(req);
            var body = await resp.Content.ReadAsStringAsync();
            if (!resp.IsSuccessStatusCode)
                throw new HttpRequestException($"Scryfall /cards/collection returned HTTP {(int)resp.StatusCode}: {body[..Math.Min(300, body.Length)]}");

            var parsed = JsonSerializer.Deserialize<ScryfallCollectionResponseDto>(body, JsonOpts())
                ?? new ScryfallCollectionResponseDto();
            foreach (var c in parsed.Data)
            {
                // Store under the ORIGINAL name (e.g. the full "Front // Back"), not the query name,
                // so callers can look results up by the name they actually have (e.g. from a decklist).
                var originalName = queryToOriginal.TryGetValue(c.Name, out var orig) ? orig : c.Name;
                result[originalName] = c.ToModel();
            }
            foreach (var nf in parsed.NotFound ?? new List<ScryfallNotFoundDto>())
            {
                if (nf.Name == null) continue;
                var originalName = queryToOriginal.TryGetValue(nf.Name, out var orig) ? orig : nf.Name;
                notFound.Add(originalName);
            }

            if (i + BatchSize < queryNames.Count) await Task.Delay(100);
        }
        return new ScryfallLookupResult(result, notFound);
    }

    /// <summary>
    /// Downloads and parses the Oracle Tags bulk file, returning oracle_id -> [tag labels].
    /// This file is regenerated by Scryfall every 12-24 hours (per their bulk-data docs) —
    /// cache the result locally (see Phase 3 checklist) rather than re-downloading per run.
    ///
    /// The file itself is a gzipped JSONL archive (.jsonl.gz) — that's file-level gzip, NOT HTTP
    /// Content-Encoding, so HttpClient's automatic decompression doesn't apply. It has to be
    /// explicitly gunzipped after download, then read one JSON object per line (JSONL isn't a
    /// JSON array). Streaming avoids loading a potentially large decompressed file into memory
    /// all at once, which is also what Scryfall's own docs recommend.
    /// </summary>
    public async Task<Dictionary<string, List<string>>> FetchOracleTagsAsync()
    {
        var listResp = await _http.GetStringAsync("https://api.scryfall.com/bulk-data");
        var list = JsonSerializer.Deserialize<BulkDataListDto>(listResp, JsonOpts()) ?? new BulkDataListDto();
        var tagsEntry = list.Data.FirstOrDefault(d => d.Type == "oracle_tags")
            ?? throw new InvalidOperationException("No 'oracle_tags' entry found in Scryfall's bulk-data listing.");

        var byOracleId = new Dictionary<string, List<string>>();
        int lineNumber = 0;

        await using var compressedStream = await _http.GetStreamAsync(tagsEntry.EffectiveDownloadUri);
        await using var gzipStream = new System.IO.Compression.GZipStream(compressedStream, System.IO.Compression.CompressionMode.Decompress);
        using var reader = new StreamReader(gzipStream);

        string? line;
        while ((line = await reader.ReadLineAsync()) != null)
        {
            lineNumber++;
            if (string.IsNullOrWhiteSpace(line)) continue;

            OracleTagRecordDto? record;
            try
            {
                record = JsonSerializer.Deserialize<OracleTagRecordDto>(line, JsonOpts());
            }
            catch (JsonException ex)
            {
                // NOTE: the per-line record shape (OracleTagRecordDto) is still a best-effort
                // guess — I haven't parsed a confirmed real line in this environment (blocked by
                // the same network allowlist issue as everything else Scryfall/EDHREC-related).
                // If this throws on line 1, print `line` directly and compare its actual field
                // names against OracleTagRecordDto — that's the fastest fix.
                throw new JsonException(
                    $"Failed to parse JSONL line {lineNumber} as OracleTagRecordDto: {ex.Message}. " +
                    $"Raw line (first 300 chars): {line[..Math.Min(300, line.Length)]}", ex);
            }
            if (record?.Taggings == null) continue;

            foreach (var tagging in record.Taggings)
            {
                if (string.IsNullOrWhiteSpace(tagging.OracleId)) continue;
                if (!byOracleId.TryGetValue(tagging.OracleId, out var tagList))
                    byOracleId[tagging.OracleId] = tagList = new List<string>();
                tagList.Add(record.Label);
            }
        }
        return byOracleId;
    }

    /// <summary>Attach OTags to each card in-place, joining on OracleId (not name).</summary>
    public void AttachTags(IEnumerable<ScryfallCard> cards, Dictionary<string, List<string>> tagsByOracleId)
    {
        foreach (var card in cards)
        {
            if (card.OracleId != null && tagsByOracleId.TryGetValue(card.OracleId, out var tags))
                card.OTags = tags;
        }
    }

    /// <summary>
    /// Same as FetchOracleTagsAsync, but reads/writes a local JSON cache file first, so the
    /// (large, gzip-compressed) bulk file only gets re-downloaded when the cache is missing or
    /// older than maxAge. Scryfall regenerates the source file roughly every 12-24 hours anyway,
    /// so there's no benefit to fetching it more often than that — a weekly refresh is plenty
    /// for how often deck contents actually change tag-relevant text.
    /// </summary>
    public async Task<Dictionary<string, List<string>>> FetchOracleTagsCachedAsync(
        string cachePath = "data/oracle-tags-cache.json",
        TimeSpan? maxAge = null)
    {
        maxAge ??= TimeSpan.FromDays(7);

        if (File.Exists(cachePath))
        {
            var age = DateTime.UtcNow - File.GetLastWriteTimeUtc(cachePath);
            if (age < maxAge)
            {
                var cached = await File.ReadAllTextAsync(cachePath);
                var deserialized = JsonSerializer.Deserialize<Dictionary<string, List<string>>>(cached, JsonOpts());
                if (deserialized != null) return deserialized;
            }
        }

        var fresh = await FetchOracleTagsAsync();
        var dir = Path.GetDirectoryName(cachePath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        await File.WriteAllTextAsync(cachePath, JsonSerializer.Serialize(fresh));
        return fresh;
    }

    private static JsonSerializerOptions JsonOpts() => new() { PropertyNameCaseInsensitive = true };
}
